import { NextRequest, NextResponse } from "next/server";
import { getAdminDb } from "@/lib/firebase-admin";

const ZODIAC_SIGNS = [
  "aries", "taurus", "gemini", "cancer", "leo", "virgo",
  "libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces",
];

function getDateKey(offset: number = 0): string {
  const now = new Date();
  now.setUTCDate(now.getUTCDate() + offset);
  return `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}-${String(now.getUTCDate()).padStart(2, "0")}`;
}

function getWeekKey(): string {
  const now = new Date();
  const start = new Date(Date.UTC(now.getUTCFullYear(), 0, 1));
  const diff = now.getTime() - start.getTime();
  const oneWeek = 1000 * 60 * 60 * 24 * 7;
  const weekNum = Math.floor(diff / oneWeek);
  return `${now.getUTCFullYear()}-W${weekNum}`;
}

function getMonthKey(): string {
  const now = new Date();
  return `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}`;
}

/**
 * GET /api/horoscope/sign?sign=cancer&period=daily
 * Serves pre-generated sign-based horoscopes from Firestore.
 * These are generated by the /api/cron/generate-horoscopes endpoint.
 */
export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const sign = searchParams.get("sign")?.toLowerCase();
  const period = searchParams.get("period") || "daily"; // daily, tomorrow, weekly, monthly

  if (!sign || !ZODIAC_SIGNS.includes(sign)) {
    return NextResponse.json(
      { success: false, error: "Valid zodiac sign is required" },
      { status: 400 }
    );
  }

  // Determine cache key
  let cacheTimeKey: string;
  if (period === "tomorrow") {
    cacheTimeKey = getDateKey(1);
  } else if (period === "weekly") {
    cacheTimeKey = getWeekKey();
  } else if (period === "monthly") {
    cacheTimeKey = getMonthKey();
  } else {
    cacheTimeKey = getDateKey();
  }

  const adminDb = getAdminDb();
  const cacheDocId = `sign_${period}_${sign}_${cacheTimeKey}`;

  try {
    const docSnap = await adminDb.collection("horoscopes").doc(cacheDocId).get();

    if (docSnap.exists) {
      const data = docSnap.data();
      return NextResponse.json({
        success: true,
        data: data?.horoscope_data,
        sign,
        period,
        date: cacheTimeKey,
        cached: true,
      });
    }

    // Not pre-generated yet
    return NextResponse.json(
      { success: false, error: "Horoscope not yet generated. Please try again later." },
      { status: 404 }
    );
  } catch (error: any) {
    console.error("Sign horoscope fetch error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch horoscope" },
      { status: 500 }
    );
  }
}
